name: Build tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  basic-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: make
      run: make CC=gcc
    - name: make clean
      run: make clean
    - name: make fclean
      run: make fclean
    - name: make re
      run: make CC=gcc re
    - name: check binary
      run: ls -l ./42sh
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

  cs-build:
    needs: [basic-build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Copy Dockerfile inside root
      run : cp ./.github/Dockerfile ./Dockerfile
    - name: Build coding-style tests
      run: docker build . -t cs-test --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run basic command
      run : docker run cs-test:latest
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
  
  coverage-build:
    needs: [basic-build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Copy Dockerfile inside root
      run : cp ./.github/Dockerfile2 ./Dockerfile
    - name: Build coverage-style tests
      run: docker build . -t coverage-test --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run basic command
      run : docker run coverage-test:latest
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

  valgrind-build:
    needs: [basic-build]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
    - name: update apt
      run : sudo apt-get update
    - name: setup valgrind
      run:  sudo apt-get install -y valgrind
    - name: make
      run: make CC=gcc
    - name: check file
      run: ls -l ./42sh
    - name: run valgrind
      run: valgrind --leak-check=full --show-leak-kinds=all ./42sh ./.github/test.c
    - name: clean
      run: make fclean
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

  scan-build-test:
    needs: [basic-build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Copy Dockerfile inside root
      run : cp ./.github/Dockerfile3 ./Dockerfile
    - name: Build scan-build tests
      run: docker build . -t scan-build-test --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run scan-build tests
      run : docker run scan-build-test:latest
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
