name: Sync from orga

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone orga repo
        run: |
          git clone git@github.com:EpitechPGE1-2025/G-PSU-200-MPL-2-1-42sh-5.git upstream
          cd upstream
          git remote add mirror git@github.com:Willi363363/my-42sh-mirror.git
          git push mirror main --force

